import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Brief = { id:string; account:string; owner:string; region:string; segment:string; regulator:string; problem:string; systems:string[]; expected_timeline:string; success_criteria:string[]; received_at:string };
type Match = { template:{id:string;name:string;region:string;segment:string;problem_solved:string;capabilities:string[];integrations:string[];outcome:string}; score:number; reasons:string[] };
type Item = { brief:Brief; health:{status:string;elapsed_business_days:number;elapsed_business_hours:number}; draft?:{draft:any;matches:Match[];provider:string}; trigger?:any };
const API = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000';

async function request(path:string, init?:RequestInit){ const r=await fetch(`${API}${path}`,{headers:{'Content-Type':'application/json'},...init}); const body=await r.json().catch(()=>({})); if(!r.ok) throw new Error(body.detail?.message || body.detail || body.error?.message || 'Request failed'); return body; }

function App(){
  const [items,setItems]=useState<Item[]>([]); const [selected,setSelected]=useState<Item|null>(null); const [provider,setProvider]=useState<'gemini'|'lm_studio'>('gemini'); const [matches,setMatches]=useState<Match[]>([]); const [draft,setDraft]=useState<any>(null); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [loading,setLoading]=useState(false);
  const load=async()=>{try{const data=await request('/api/briefs'); setItems(data.items); setSelected(current=>current ? data.items.find((x:Item)=>x.brief.id===current.brief.id)||data.items[0] : data.items[0]);}catch(e){setError(String(e))}};
  useEffect(()=>{load(); const timer=setInterval(load,15000); return()=>clearInterval(timer)},[]);
  useEffect(()=>{if(selected?.draft){setDraft(selected.draft.draft);setMatches(selected.draft.matches)} else {setDraft(null);setMatches([])}},[selected]);
  const generate=async()=>{if(!selected)return;setLoading(true);setError('');setNotice('');try{const data=await request(`/api/briefs/${selected.brief.id}/generate`,{method:'POST',body:JSON.stringify({provider})});setDraft(data.draft);setMatches(data.matches);setNotice(`Draft generated with ${provider === 'gemini'?'Gemini':'LM Studio'}.`);await load()}catch(e){setError(String(e))}finally{setLoading(false)}};
  const decide=async(decision:'accepted'|'rejected')=>{if(!selected||!draft)return;const reason=decision==='rejected'?window.prompt('Why is this draft rejected?'):null;if(decision==='rejected'&&!reason)return;try{const data=await request(`/api/briefs/${selected.brief.id}/decision`,{method:'POST',body:JSON.stringify({decision,draft,rejection_reason:reason})});setNotice(`${decision} recorded. Reuse rate: ${Math.round(data.reuse_rate*100)}%.`);await load()}catch(e){setError(String(e))}};
  if(!selected)return <main className="shell"><h1>RevenueOS</h1><p>Loading brief queue…</p></main>;
  const b=selected.brief; return <main className="shell"><header className="topbar"><div><p className="eyebrow">Synthetic RevenueOS control surface</p><h1>Brief → POC Plan</h1><p className="sub">Sales → US PreSales handoff operations</p></div><div className="provider"><label>Agent provider<select value={provider} onChange={e=>setProvider(e.target.value as any)}><option value="gemini">Gemini</option><option value="lm_studio">LM Studio</option></select></label><button className="primary" onClick={generate} disabled={loading}>{loading?'Generating…':'Generate draft'}</button></div></header>
    {error&&<div className="error"><strong>Provider/request error</strong><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}{notice&&<div className="notice">{notice}</div>}
    <section className="grid"><aside className="panel queue"><div className="panel-title"><h2>Brief queue</h2><span>{items.length} open</span></div>{items.map(item=><button className={`queue-item ${item.brief.id===b.id?'active':''}`} key={item.brief.id} onClick={()=>setSelected(item)}><div><strong>{item.brief.account}</strong><small>{item.brief.segment.replace('_',' ')} · {item.brief.region}</small></div><span className={`badge ${item.health.status.toLowerCase()}`}>{item.health.status}</span></button>)}</aside>
    <div className="content"><section className="panel brief"><div className="panel-title"><div><p className="eyebrow">{b.id} · {b.owner}</p><h2>{b.account}</h2></div><span className={`badge ${selected.health.status.toLowerCase()}`}>{selected.health.status}</span></div><div className="facts"><div><small>Region / segment</small><strong>{b.region} · {b.segment.replace('_',' ')}</strong></div><div><small>Regulator</small><strong>{b.regulator}</strong></div><div><small>Brief age</small><strong>{selected.health.elapsed_business_days} business days</strong></div><div><small>Pickup SLA</small><strong>2 business days</strong></div></div><p>{b.problem}</p><div className="chips">{b.systems.map(x=><span key={x}>{x}</span>)}</div></section>
    <section className="panel"><div className="panel-title"><h2>Retrieval reasoning</h2><span>Top {matches.length || 0} matches</span></div>{matches.length===0?<p className="muted">Generate a draft to retrieve prior solutions.</p>:<div className="matches">{matches.map(m=><article className="match" key={m.template.id}><div><strong>{m.template.name}</strong><small>{m.template.id} · {m.template.region} · {Math.round(m.score*100)}% match</small></div><ul>{m.reasons.map(r=><li key={r}>{r}</li>)}</ul><p>{m.template.outcome}</p></article>)}</div>}</section>
    <section className="panel draft"><div className="panel-title"><h2>POC plan & Delivery handoff</h2><span>{draft?'Editable draft':'No draft yet'}</span></div>{draft?<><label>Objective<textarea value={draft.poc_plan.objective} onChange={e=>setDraft({...draft,poc_plan:{...draft.poc_plan,objective:e.target.value}})}/></label><div className="two"><label>Scope in<textarea value={draft.poc_plan.scope_in.join('\n')} onChange={e=>setDraft({...draft,poc_plan:{...draft.poc_plan,scope_in:e.target.value.split('\n')}})}/></label><label>Risks<textarea value={draft.poc_plan.risks.join('\n')} onChange={e=>setDraft({...draft,poc_plan:{...draft.poc_plan,risks:e.target.value.split('\n')}})}/></label></div><label>Delivery handoff<textarea value={draft.delivery_handoff.solution_summary} onChange={e=>setDraft({...draft,delivery_handoff:{...draft.delivery_handoff,solution_summary:e.target.value}})}/></label><div className="actions"><button onClick={()=>decide('rejected')} className="secondary">Reject</button><button onClick={()=>decide('accepted')} className="primary">Accept & record</button></div></>:<p className="muted">Choose a provider and generate an actionable POC plan.</p>}</section>
    <section className="panel trigger"><div className="panel-title"><h2>Trigger log</h2><span>Computed from events</span></div>{selected.trigger?<div className="trigger-row"><span className="badge red">RED</span><div><strong>Two-business-day SLA breach</strong><p>Owner: {selected.trigger.owner} · {selected.trigger.context.elapsed_business_days} business days elapsed</p></div></div>:<p className="muted">No breach trigger for this brief.</p>}</section></div></section></main>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);

